### PR TITLE
JOHNZON-131: JSON-B Requires Non-Exported Internal Package from Mapper

### PR DESCRIPTION
**Pull request by jwcarman**

### CODE REVIEW

**Comment by struberg** [comment]
Thanks James! PR got applied in commit 2f0cb1b54bb216280ba55b71373d
Not sure how to close it here on github though ;)

**Comment by rmannibucau** [comment]
Still needed?

**Comment by rmannibucau** [comment]
guess it is fixed by osgi module?

**Comment by jeanouii** [comment]
Yes applied already. Closing

**Pull request closed without merging**
