### PR TITLE
Fixes merged from trunk

### PR DESCRIPTION
**Pull request by jgallimore**
I'll open up a discussion on the Johnzon dev list for this, but this effectively comes from a suggestion from @rmannibucau here: http://tomee-openejb.979440.n4.nabble.com/DISCUSS-switching-TomEE8-to-master-tp4683438p4683734.html to copy master, and downgrade the APIs to match the 1.0.0 version; effectively creating a 1.0.x version with the fixes from trunk.

I'll attempt to cross-reference this to the set of JIRAs that this would cover and verify them as well.

Any feedback is most welcome. Thanks in advance for your consideration.

### CODE REVIEW

**Comment by avermeer** [comment]
Hello Jon,

So far so good : I built a Johnzon-1.0.1-snapshot version based on your PR, and at least two of our top issue with JAX-RS in TomEE+ 7.0.4 are solved. I have one more pending issue to check with this version, I'll give final feedback ASAP.

Best regards,
Alexandre

**Comment by avermeer** [comment]
Hello Jon,

Yet another good news : the pending test which I was referring to in my previous post is... **OK** !!
  I am going to deliver the Johnzon-1.0.1-snapshot version based on your PR into our SCM system on our "latest" branch so that this will bring a more pervasive test of this snapshot.
  I should be able to give complete assessment by the end of next week.

Best regards,
Alexandre

**Comment by jgallimore** [comment]
Fantastic news. Thank you very much for the testing and feedback, its much appreciated.

**Comment by rmannibucau** [comment]
+1 to merge from me

**Comment by jeanouii** [comment]
Should be all merged. Re-open if not.

**Pull request closed without merging**
