### PR TITLE
JOHNZON-279 Fails to build on Travis CI (Xenial)

### PR DESCRIPTION
**Pull request by mkarg**
Seems there are several causes.

Cause 1: https://travis-ci.community/t/install-of-oracle-jdk-8-failing

Cause 2: "The job exceeded the maximum log length, and has been terminated."

### CODE REVIEW

**Comment by mkarg** [comment]
@rmannibucau Switching to openjdk8 + using `mvn -q` fixes the Travis CI build, but the `-q` drops the complete Cobertura output on Travis CI. Is that ok for you?

**Comment by rmannibucau** [comment]
We dont use cobertura or coveralls in the build so no issue for me
-B is ok too for me
We can also set up the cache and set download logs as being in warn level to avoid a bunch, can speed up things if you rely on travis (since build is small we often rely on local builds for johnzon)

**Comment by mkarg** [comment]
@rmannibucau It was not nice of you to claim credits for solving this issue by copying my solution, pushing your own commit instead of my PR, and by that breaking the PR build. I spent my spare time into this solution, so at least you should have accepted the PR *before* you put your changes ontop to keep my credits. :-(

**Comment by rmannibucau** [comment]
@mkarg PR was not there when i committed the file and jira didnt mention it was coming (as you did for a few other tickets) so assumed since it was trivial and needed to be updated (we never used travis since project was added to apache) that it was just a go through task. Sorry about that. That said we still need the -B (or -q but guess B is better since we cant be interactive). If you want to go, just do please, will wait for an ack this time ;).

**Comment by mkarg** [comment]
> @mkarg PR was not there when i committed the file and jira didnt mention it was coming (as you did for a few other tickets) so assumed since it was trivial and needed to be updated (we never used travis since project was added to apache) that it was just a go through task. Sorry about that. That said we still need the -B (or -q but guess B is better since we cant be interactive). If you want to go, just do please, will wait for an ack this time ;).

Actually the PR *was* there *before*, as you even *answered* in its discussion thread (see above) one hour *before* you pushed your own solution, AND as you can see in the JIRA ticket https://issues.apache.org/jira/browse/JOHNZON-279 where clearly the PR is was linked to the ticket *before* you pushed your solution.

**To resolve the dispute and to express your regret I kindly request you to rebase `master` ontop of my PR, so credits are clear, before I go on with work on Johnzon.**.

**Comment by rmannibucau** [comment]
Just for the record:

> Actually the PR was there before

https://api.github.com/repos/apache/johnzon/pulls/49 -> your PR was done at 2019-09-23T17:33:12Z
https://api.github.com/repos/apache/johnzon/commits/d99eb3f41276644d7f178ffb76f22eacf99fe93a -> my commit was done at 2019-09-23T17:28:15Z

So strictly speaking your last comment is a bit unfair since I pushed before you PR-ed so the PR link in the jira was updated after the fix was pushed so at the end credits are clear (to be very explicit, current travis.yml credit are more about https://github.com/Talend/component-runtime/blob/master/.travis.yml than your PR).

Now, I personally don't care much about public credit (I only care about projects) so I am happy to drop my last commit if you integrate the changes in travis.yml (https://github.com/apache/johnzon/pull/49#issuecomment-534287843: cache, drop after_install, and probably openjdk11 support to not loose it).

Side note question which was probably not clear in the mentionned commit: do you use travis for your personal dev? If not we can also just drop the file since nobody uses it (you hit that issue quite late regarding your previous contributions so not sure you use it or just spotted the issue during another hack).

**Comment by mkarg** [comment]
@rmannibucau I am sorry for accusing you, it just looked different from my side. I checked the logs again, and you are right, apparently we worked roughtly in parallel on that issue and pushed just minutes in sequence. It seems we both were too eagerly hacking code; we should more clearly put markers in the JIRA when we start on an issue. (Unfortunately we cannot use the JIRA assignee feature as only committers can be set there).

Regarding the outcome of our dispute: As not being paid for this actually I do care **a lot** about credits on all the open source work I did in the past 20+ years. As we both worked on the same issue actually, my proposal would be to drop your commit, and accept my PR, and put your commit ontop of it. So both solutions are mentioned correctly. I think this would be most fair to both of us. Again, sorry for the confusion.

Regarding Travis itself, I just fixed it in the first place solely because it kept sending me error messages. I do not _rely_ on the outcome. On the other hand, as it is fixed now, why should we drop it? It comes in really handy actually (I'm used to it from other open source projects, like JAX-RS, where we actually rely on it by blocking Github Merge button). As the nightly builds of Johnzon are apparently broken anyways, we could instead add the nightly builds to Travis CI instead of dropping it? Anyways, I am not the project lead. This is not my decision.

**Comment by rmannibucau** [comment]
@mkarg why not? Because not sure anyone wants to put personal credentials on travis. If we want such a thing we need to go through infra team (at ASF) I guess. My personal point asking about dropping it was that it is not maintained since nobody uses it anymore so thought it can be saner to just drop it even if I agree Travis is not bad (I'm using it at work too).

I guess it can be worth a thread on dev@johnzon to ensure we dont invest in making it fully working for nothing, let me start the thread and see the outcome before moving forward on that topic. I'll comment there in a few days when we'll get feedback (feel free to pop up in the thread BTW ;)).

**Comment by mkarg** [comment]
@rmannibucau Great! I will follow your thread. :-)

**Comment by mkarg** [comment]
@rmannibucau Now that 1.2-SNAPSHOT is not existing anymore (hence: our fixes live in 1.2.1-SNAPSHOT now), the question for a nightly build gets rather urgent for us. Can you please start the mentioned discussion. That would be great! If there is no chance for getting this soon just tell me and I will set up a nightly build on my own fork/repo.

**Comment by struberg** [comment]
Will do a deploy manually, and thanks for the PR and report!

**Comment by mkarg** [comment]
@struberg Well... what actually did you deploy manually and where to...? :thinking:

**Comment by struberg** [comment]
oh, https://repository.apache.org/content/groups/snapshots/
This is our official ASF snapshots repo.

**Comment by rmannibucau** [comment]
no more travis build so guess we can close

**Pull request closed without merging**
