### PR TITLE
Fix long number parse in collections, and unify non-integral parse

### PR DESCRIPTION
**Pull request by kumm**
On one code path non-integrals parsed as Double, on the other path
as BigDecimal.
Now it's always BigDecimal.

### CODE REVIEW

**Comment by rmannibucau** [comment]
Hello @kumm , a few comments:

1. the map handling was intentional cause it doesn't target big numbers generally but only small ones (config). However we can enhance it a bit as you propose.
2. the convertTo new handling is however a regression in term of performance and behavior since double numbers become bigdecimal so you need to adapt. Don't forget to revert the deletion you did in the test, it is more important to support double than BigDecimal.

Overall I think the idea is good but ensure you use (in order) these types:

1. int
2. long
3. double
4. BigDecimal

cause it is the way it is casted in practise and rarely with a type check before (kind of implicit contract in term of usage I'd say).

Can you update this PR to support double please and add it back in the test?

**Comment by kumm** [comment]
yes, I am going to update this.

**Comment by kumm** [comment]
I'm not sure it's a good strategy to decide whether the JsonNumber should be a Double or BigDecimal.
It depends on use-case. 
Any feedback are welcome.

**Comment by rmannibucau** [comment]
If you think about Map<String, ?> usage it is rarely for very big numbers, more for config and direct double casting is often done cause you know what kind of number you get. If you have another proposal I'm happy to discuss it (I'm not 100% happy too with this stratégy).

**Comment by kumm** [comment]
What about a MapperConfig setting?
Something like USE_BIG_DECIMAL_FOR_FLOATS here: https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features

**Comment by rmannibucau** [comment]
sounds good to me

**Comment by kumm** [comment]
should I implement it as a new PR (new story), on top of this, or just update this one?

**Comment by rmannibucau** [comment]
there is fine, guess you will just replace some existing conditions by the new flag

**Comment by kumm** [comment]
missed to comment after update, but it's updated

**Comment by rmannibucau** [comment]
Looks almost good for me, only missing part if the wiring of that config in the exposed object like *Provider (JAXRS providers), can you add it (just a setter returning void generally). Except that it is a great patch!

**Comment by kumm** [comment]
Thanks, done.
Just a question: setSerializeValueFilter intentionally left out from WildcardConfigurableJohnzonProvider?

**Comment by rmannibucau** [comment]
Dont think so, pby a miss

**Comment by rmannibucau** [comment]
applied, thanks a lot @kumm

**Comment by kumm** [comment]
It was a pleasure.
Closing it.

**Pull request closed without merging**
